# Generated by Django 5.0.6 on 2025-06-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('profesor', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='fotos')),
                ('disponibilidad', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duracion', models.DurationField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
